server:
  port: 8761  #端口号
eureka:
  client:
    register-with-eureka: false #是否将当前服务当做客户端进行注册  一般为false
    fetch-registry: false #是否同步其他eurekaserver的数据
    service-url:
      defaultZone: http://localhost:8761/eureka/  #祖册中心的访问地址

